import java.util.Scanner;

class S2Assignment1 {

public static void main(String[] args){

//Declaring variables and assigning the value

int age;
System.out.print ("Enter Your age:");
Scanner obj1= new Scanner(System.in);
age=obj1.nextInt();

if (age>=18){

System.out.println ("You are eligible for vote.");}

else if (age<18){

System.out.println ("You are not eligible for vote.");}
		




}
}


